import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import "./globals.css";

// Import Images
import infinite_icon from "../public/infinite-icon.svg";
import infinite_logo_black from "../public/infinite-logo-black.svg";
import infinite_logo_white from "../public/infinite-logo-white.svg";

// Define metadata for the page
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <header>
          <Link href={
            {
              pathname: "/",
            }
          }>
            <Image id="header-infinite-icon" src={infinite_icon} alt="" />
          </Link>
          <Image src={infinite_logo_white} alt="THE INFINITY'S" className="dark-mode header-infinite-logo" />
          <Image src={infinite_logo_black} alt="THE INFINITY'S" className="light-mode header-infinite-logo" />
        </header>
        <main>
          {children}
        </main>
        <footer></footer>
      </body>
    </html>
  );
}
